### ISSUE TITLE
Support --

### ISSUE THREAD

**Issue by AndrewVos** [AndrewVos/op#1]
@injekt

**Comment by leejarvis** [comment]
Any options after the `--` should be ignored:

```
--foo bar -- --baz etc
```

`--baz etc` should be left in the original list of arguments, `--foo bar` should be parsed as normal. You should basically ignore anything that happens after the `--`, in Slop I actually break out of the main loop when I see `--`.

**Comment by AndrewVos** [comment]
This reminds me of something. Should I be duping the arguments parameter, so as not to mess with ARGV?

**Comment by leejarvis** [comment]
That depends. In Slop I have a `parse` which does not modify the original object, and `parse!` which does. Both are useful, the latter in fact probably more so (that way a user can test against the original object to extract more arguments or check if they're empty). Option parser also does this
